name: Email CI Workflow with Cache

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v4
        with:
          path: ~/.cache
          key: cache-31f1bae

      - name: prime-cache-31f1bae
        run: echo "Cache hit? ${{ steps.cache.outputs.cache-hit }}"

      - name: 25ds3000027@ds.study.iitm.ac.in
        run: echo "Workflow with caching complete!"
